### ISSUE TITLE
Make explicit the copyright terms of this work.

### ISSUE THREAD

**Issue by lvella** [wilsonwastaken/BCH-design#3]
Having been designed to be used by anyone everywhere, in the spirit of open source and Bitcoin Cash, I recommend using [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/), which is the most permissive of the Creative Commons licenses. Make it clear on the README what license this work is distributed under, and link the page/text of the chose license.

**Comment by wilsonwastaken** [comment]
hey, thanks for helping me out! added svgs of everything and more. 

and for the license... just add this link in the read me? https://creativecommons.org/licenses/by/4.0/legalcode

**Comment by lvella** [comment]
I believe the same address I linked is enough (the general summary instead of the complete legal text). if someone is interested in the legal text, can follow from there.
